# Environment contexts:
# master/main: production
# other context depends on the branch name: testing, staging etc.
[build]
  command = "npm run build"
  publish = "out"
  environment = { NODE_VERSION =  "14", NPM_VERSION = "7", NPM_FLAGS = "--legacy-peer-deps"}

[[plugins]]
  package = "@netlify/plugin-nextjs"

[context.new]
  [context.testing.environment]
    APP_API_ENDPOINT= ""

[context.staging]
  [context.staging.environment]
    APP_API_ENDPOINT= ""

[context.production]
  [context.production.environment]
    APP_API_ENDPOINT= ""



